application: kesikesi-me
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: web/css

- url: /images
  static_dir: web/images

- url: /js
  static_dir: web/js

- url: /api/api_test
  script: api.py
  login: admin

- url: /api/.*
  script: api.py
  
- url: /page/archive
  secure: always
  script: archive.py

- url: /page/api/archive_read_more
  secure: always
  script: archive.py
  
- url: /page/settings
  secure: always
  script: settings.py
  
- url: /page/settings/google
  secure: always
  login: required
  script: settings.py

- url: /
  script: main.py
  
- url: /.*
  script: image.py

  